### ISSUE TITLE
Very many pages

### ISSUE THREAD

**Issue by anu-vaid** [bootstrap-ruby/will_paginate-bootstrap#3]
Is there a way to introduce a disabled gap in the middle if there are many pages?

**Comment by poombavai** [comment]
Hi.. inner_window and outer_window doesnot showing me any changes in my page.. I have tried like,
my views,  
  <%= will_paginate @issue, page_links: true, inner_window: 2, outer_window: 1 %>
my controller, 
    @issue = Issue.all.paginate(page: params[:page], per_page: 5).order("issue_slip_no DESC")
.. 
How should I correct it?

**Comment by zhukovRoman** [comment]
@poombavai I have this problem too. Did you solve it?

**Comment by poombavai** [comment]
@zhukovRoman No. Not yet. Tried pagination with Kaminari gem.

**Comment by poombavai** [comment]
@zhukovRoman No. Not yet. Tried pagination with Kaminari gem.
