### ISSUE TITLE
Deprecated Fixnum on Ruby v2.4.0+

### ISSUE THREAD

**Issue by Xosmond** [bootstrap-ruby/will_paginate-bootstrap#53]
https://github.com/bootstrap-ruby/will_paginate-bootstrap/blob/1a0d7b3af5a314f9046714c6356a750d0a6197e2/lib/bootstrap_pagination/bootstrap_renderer.rb#L11

Deprecated by Integer on Ruby 2.4.0+

Source: https://bugs.ruby-lang.org/issues/12005

**Comment by acaporrini** [comment]
I made a PR to fix it

https://github.com/bootstrap-ruby/will_paginate-bootstrap/pull/56

**Comment by jalada** [comment]
Looks like this is fixed in the undocumented 1.0.2 that's on RubyGems:

![Screenshot 2019-06-28 at 09 49 41](https://user-images.githubusercontent.com/126989/60330314-1518e380-998a-11e9-8fe8-5de005383836.png)
